name: Linting

on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Subdirectory to avoid linting luarocks code. Use same dir as testy.
        path: batteries
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: 5.4
    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup luacheck
      run: luarocks install luacheck
    - name: Run Code Linter
      run: |
        cd batteries
        luacheck .
